// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.HttpServiceProxy.Legacy.Proxy
{
    using Intent.SoftwareFactory.MetaModels.UMLModel;
    using Intent.SoftwareFactory.Templates;
    using Intent.SoftwareFactory.MetaModels.Service;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class WebApiClientServiceProxyTemplate : IntentRoslynProjectItemTemplateBase<ServiceModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n\r\nusing System;\r\nusing System.Configuration;\r\nusing System.Linq;\r\nusing System" +
                    ".Net.Http;\r\nusing System.Net.Http.Headers;\r\nusing System.Threading.Tasks;\r\n");
            
            #line 22 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DependencyUsings));
            
            #line default
            #line hidden
            this.Write("\r\nusing Intent.CodeGen; \r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnames" +
                    "pace ");
            
            #line 27 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 29 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 29 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private readonly IHttpProxyInterceptor[] _httpProxyInterceptors;" +
                    "\r\n\r\n        public ");
            
            #line 33 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"(IHttpProxyInterceptor[] httpProxyInterceptors) 
        {
            _httpProxyInterceptors = httpProxyInterceptors;
        }

        private HttpClient CreateHttpClient()
        {
            var serviceName = ConfigurationManager.AppSettings[""WebApiEndpointBaseUrl.");
            
            #line 40 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationName));
            
            #line default
            #line hidden
            this.Write("\"];\r\n            if (string.IsNullOrWhiteSpace(serviceName))\r\n            {\r\n    " +
                    "            throw new Exception(\"No configuration entry defined. Please add the " +
                    "following to the config file\'s appSetting section: <add key=\\\"WebApiEndpointBase" +
                    "Url.");
            
            #line 43 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationName));
            
            #line default
            #line hidden
            this.Write(@"\"" value=\""INSERT_URL_HERE\"" />"");
            }

            int timeoutInSeconds;
            if (!int.TryParse(ConfigurationManager.AppSettings[""HttpClient.Timeout.Seconds""], out timeoutInSeconds))
            {
                throw new Exception(""Could not find or parse 'HttpClient.Timeout.Seconds' setting in config file as int."");
            }

            var client = new HttpClient
            {
                BaseAddress = new Uri(new Uri(serviceName), ""/api/");
            
            #line 54 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.Replace("Service", "").ToLower()));
            
            #line default
            #line hidden
            this.Write(@"/""),
                Timeout = TimeSpan.FromSeconds(timeoutInSeconds)
            };

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(""application/json""));

            foreach(var httpProxyInterceptor in _httpProxyInterceptors)
            {
                httpProxyInterceptor.OnCreate(client);
            }

            return client;
        }

");
            
            #line 69 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

    foreach (var operation in Model.Operations)
    {

            
            #line default
            #line hidden
            
            #line 73 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

        // Asynchronous versions:
        if (operation.HasReturnType())
        {

            
            #line default
            #line hidden
            this.Write("        public async Task<");
            
            #line 78 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnType.FullName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 78 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 78 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodDefinitionParameters(operation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return await new Task<");
            
            #line 80 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnType.FullName));
            
            #line default
            #line hidden
            this.Write(">(() => ");
            
            #line 80 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 80 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodCallParameters(operation)));
            
            #line default
            #line hidden
            this.Write("));\r\n        }\r\n\r\n");
            
            #line 83 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

        }
        else // if (operation.HasReturnType())
        {

            
            #line default
            #line hidden
            this.Write("        public async void ");
            
            #line 88 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 88 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodDefinitionParameters(operation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            await new Task(() => ");
            
            #line 90 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 90 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodCallParameters(operation)));
            
            #line default
            #line hidden
            this.Write("));\r\n        }\r\n\r\n");
            
            #line 93 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
 
        } // if (operation.HasReturnType())

        // Synchronous versions:

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 98 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.HasReturnType() ? operation.ReturnType.FullName : "void"));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 98 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 98 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodDefinitionParameters(operation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            using (var client = CreateHttpClient())\r\n            {\r" +
                    "\n                try\r\n                {\r\n                    const string reques" +
                    "tUri = \"");
            
            #line 104 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToLowerInvariant()));
            
            #line default
            #line hidden
            this.Write("\";\r\n                    \r\n                    var response = client.PostAsJsonAsy" +
                    "nc(\r\n                        requestUri: requestUri,\r\n");
            
            #line 108 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
 
                    if (operation.UsesRawSignature)
                    {

                        if (operation.Parameters.Count > 1)
                        {
                            throw new Exception(string.Format("Use of more than one parameter for operations which have 'IsRaw' is unsupported. Service='{0}', Operation='{1}'", Model.Name, operation.Name));
                        }

            
            #line default
            #line hidden
            this.Write("                        value: ");
            
            #line 117 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Parameters.Any() ? operation.Parameters.Single().Name : "null"));
            
            #line default
            #line hidden
            this.Write(").Result;\r\n");
            
            #line 118 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("                        value: new\r\n                        {\r\n");
            
            #line 125 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

                        foreach (var parameter in operation.Parameters)
                        {

            
            #line default
            #line hidden
            this.Write("                            ");
            
            #line 129 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 130 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

                        } // foreach (var parameter in operation.Parameters)

            
            #line default
            #line hidden
            this.Write("                        }).Result;\r\n");
            
            #line 134 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
 
                    }

            
            #line default
            #line hidden
            this.Write(@"
                    if (!response.IsSuccessStatusCode)
                    {
                        throw new WebApiClientServiceProxyRemoteException(
                            response.StatusCode,
                            response.ReasonPhrase,
                            $""Request to {new Uri(client.BaseAddress, requestUri).AbsoluteUri} failed with status code {(int)response.StatusCode} {response.ReasonPhrase}.\n\n"" +
                            $""{response.Content.ReadAsStringAsync().Result}"");
                    }
");
            
            #line 146 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

            if (operation.HasReturnType())
            {

            
            #line default
            #line hidden
            this.Write("\r\n                    return response.Content.");
            
            #line 151 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReadAs(operation)));
            
            #line default
            #line hidden
            this.Write(".Result;\r\n");
            
            #line 152 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

            } // if (operation.HasReturnType())

            
            #line default
            #line hidden
            this.Write(@"                }
                catch (AggregateException aggregateException)
                {
                    if (aggregateException.InnerExceptions.Count == 1)
                    {
                        throw aggregateException.InnerExceptions.Single();
                    }

                    throw;
                }
            }
        }

");
            
            #line 168 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.HttpServiceProxy\Legacy\Proxy\WebApiClientServiceProxyTemplate.tt"

    } // foreach (var operation in Model.Operations)

            
            #line default
            #line hidden
            this.Write("        public void Dispose()\r\n        {\r\n            // NOP\r\n        }\r\n    }\r\n}" +
                    "\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
