/// <reference path="../../typings/elementmacro.context.api.d.ts" />
/// <reference path="../../typings/core.context.types.d.ts" />

interface IFieldDiscrepancy {
    id: string;
    type: "ADD" | "DELETE" | "RENAME" | "CHANGE_TYPE";
    
    sourceParentId?: string;
    sourceFieldId?: string;
    sourceFieldName: string;
    sourceFieldTypeName?: string;
    sourceTypeId?: string;
    sourceIsCollection?: boolean;
    sourceIsNullable?: boolean;

    // REPLACED: targetAttributeId & targetAssociationId with generic targetId + type discriminator
    targetId?: string;                              // Could be attribute ID or association ID
    targetIdType?: "attribute" | "association";    // Discriminator: what does targetId represent?
    targetEntityId?: string;                        // Which entity this ultimately targets (for context)
    
    targetAttributeName: string;
    targetAttributeTypeName?: string;
    targetTypeId?: string;
    targetIsCollection?: boolean;
    targetIsNullable?: boolean;
    
    // For ADD association discrepancies: the suggested DTO name to create
    suggestedDtoName?: string;
    
    mappingPath?: string[];
    reason?: string;
    icon: MacroApi.Context.IIcon;

    displayFunction?: (context: MacroApi.Context.ISelectableTreeNode) => string | MacroApi.Context.IDisplayTextComponent[];
}

interface IFieldMapping {
    sourcePath: string[];
    targetPath: string[];
    sourceFieldId: string;
    targetAttributeId: string;
    mappingType?: string;
    mappingTypeId?: string;
}

interface IPathTemplate {
    sourceDepth: number;
    targetDepth: number;
    sourceElementTypes: string[];
    targetElementTypes: string[];
    signature: string;
    mappingTypeId: string;
    mappingTypeName: string;
}

interface IEntityAttribute {
    id: string;
    name: string;
    typeId?: string;
    typeDisplayText?: string;
    icon: MacroApi.Context.IIcon;
    isManagedKey?: boolean;
    hasPrimaryKeyStereotype?: boolean;
    isCollection?: boolean;
    isNullable?: boolean;
    // Mappability checks (per Intent Architect's mapping system requirements)
    isAutoGeneratedPk?: boolean;           // PK with non-user-supplied data source
    isForeignKey?: boolean;                // Has Foreign Key stereotype
    fkIsRequiredParent?: boolean;          // FK that's non-collection and non-nullable
    isSetByInfrastructure?: boolean;       // Infrastructure-managed field
    isMappable?: boolean;                  // Final determination if this attribute can be mapped
    // Type classification (resolved from type element)
    typeName?: string;                     // Resolved type element name
    typeSpecialization?: string;           // Type element specialization
    isComplexType?: boolean;               // Whether this is a complex type
    isValueObject?: boolean;               // Whether this is a value object
}

// Hierarchical structures for generic parameter and field representation
interface IFieldNode {
    id: string;
    name: string;
    type: "Primitive" | "DTO" | "Complex";
    typeId?: string;
    typeDisplayText?: string;
    icon: MacroApi.Context.IIcon;
    isMapped?: boolean;
    mappedToId?: string;
    children?: IFieldNode[];  // For nested structures (DTO fields, nested objects)
}

interface IParameterNode {
    id: string;
    name: string;
    type: "Primitive" | "DTO" | "Complex";
    typeId?: string;
    typeDisplayText?: string;
    icon: MacroApi.Context.IIcon;
    children?: IFieldNode[];  // Only for DTO or Complex types
    isMapped?: boolean;
    mappedToId?: string;
}

interface IExtendedTreeNode extends MacroApi.Context.ISelectableTreeNode {
    elementId: string;
    elementType: string;
    originalName: string;
    originalType?: string;
    discrepancy?: IFieldDiscrepancy;
    hasDiscrepancies: boolean;

    elementParentId?: string;
    
    // NEW: Pre-computed path metadata (set during buildStructureTree)
    sourcePath?: string[];         // [rootDto, field1, field2, newField] - complete DTO path
    targetPath?: string[];         // [rootEntity, assoc1, assoc2] - path to entity (no attribute yet)
    targetEntityId?: string;       // Which entity this field targets
}
