// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.RichDomain.Templates.EntityStateInterface
{
    using Intent.SoftwareFactory.MetaModels.UMLModel;
    using Intent.SoftwareFactory.Templates;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DomainEntityStateInterfaceTemplate : IntentRoslynProjectItemTemplateBase<Class>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            
            #line 14 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"

var InterfaceName = "I" + Model.Name.ToPascalCase() + "";
var readOnlyInterfaceName = "I" + Model.Name.ToPascalCase() + "";
            
            #line default
            #line hidden
            this.Write(@"
using System;
using System.Collections.Generic;
using Intent.Framework.Domain;
using Intent.CodeGen;

[assembly: DefaultIntentManaged(Mode.Fully)]

#warning Indexes and Unqiues on FKs think its not done for 1 to Many
#warning need to factor in Aggregate boundaries into Edit and States

namespace ");
            
            #line 28 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 30 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
 if (Model.IsEntity())
   {
   
            
            #line default
            #line hidden
            this.Write("   //Typed Identifier\r\n    public class ");
            
            #line 34 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 34 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ParentClass != null ? Model.ParentClass.IdentifierType() : "Identifier"));
            
            #line default
            #line hidden
            this.Write(" \r\n    {\r\n        protected ");
            
            #line 36 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentifierType()));
            
            #line default
            #line hidden
            this.Write("(Guid id) : base (id) {}\r\n\r\n        public static ");
            
            #line 38 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(" Create(Guid? id)\r\n        {\r\n            return (id.HasValue) ? new ");
            
            #line 40 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentifierType()));
            
            #line default
            #line hidden
            this.Write("(id.Value) : null;\r\n        }\r\n    }\r\n");
            
            #line 43 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
   }
            
            #line default
            #line hidden
            this.Write("\r\n    public interface ");
            
            #line 45 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 45 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ParentClass != null ? "I" + Model.ParentClass.Name.ToPascalCase() + ", " : ""));
            
            #line default
            #line hidden
            
            #line 45 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetInterfaces(Model)));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        ");
            
            #line 47 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" State { get; }\r\n\r\n        ");
            
            #line 49 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(" Id { get; }\r\n");
            
            #line 50 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
  foreach (var attribute in Model.Attributes)
    {
        if (attribute.IsAssociationAttribute)
            continue;    

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 55 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.HasComplexDomainType() ? attribute.ComplexDomainType() : attribute.DomainType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 55 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" { get;}\r\n");
            
            #line 56 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
  }
            
            #line default
            #line hidden
            
            #line 56 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(InterfaceProperties(Model)));
            
            #line default
            #line hidden
            
            #line 56 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"

// TODO: Change this to a decorator:
	if (Model.IsAggregateRoot() && !Model.IsSubClass()) 
    {

            
            #line default
            #line hidden
            this.Write("        DateTime? CreateDateTime { get; }\r\n        DateTime? UpdateDateTime { get" +
                    "; }\r\n        string UpdatedBy { get; }\r\n\r\n");
            
            #line 65 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
  }
    foreach (var association in Model.Associations)
    {
        if (!association.Navigable)
            continue;

    if (association.OtherAssociationEnd().Multiplicity == Multiplicity.Many && association.Multiplicity == Multiplicity.One)
        {
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 73 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 73 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.IdentifierName()));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 74 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
      }
            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 76 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Type("I", "", true)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 76 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" { get;}\r\n");
            
            #line 77 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
  }
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 79 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
  foreach (var operation in Model.Operations.Where(x => x.IsQueryBehaviour()))
    {
        string returnType = operation.ReturnType != null ? operation.ReturnType.DomainType() : "void";
        string parameterDefinitions = operation.Parameters.Any() ? operation.Parameters.Select(x => x.DomainType() + " " + x.Name.ToCamelCase()).Aggregate((x, y) => x + ", " + y) : "";
        
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 84 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 84 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 84 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterDefinitions));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 85 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
    }
            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    partial class ");
            
            #line 88 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 88 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        #region ");
            
            #line 90 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        ");
            
            #line 92 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 92 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".State \r\n        { \r\n            get\r\n            {\r\n                return (");
            
            #line 96 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(")this;\r\n            }\r\n        }\r\n\r\n        ");
            
            #line 100 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 100 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".Id \r\n        { \r\n            get\r\n            {\r\n                return ");
            
            #line 104 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(".Create(this.Id);\r\n            }\r\n        }\r\n\r\n");
            
            #line 108 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
  foreach (var attribute in Model.Attributes)
    {
        if (attribute.IsAssociationAttribute)
            continue;
            
            #line default
            #line hidden
            
            #line 112 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
      if (attribute.HasComplexDomainType())
        {
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 114 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.ComplexDomainType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 114 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 114 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" \r\n        {\r\n            get { return (");
            
            #line 116 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" != null) ? new ");
            
            #line 116 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.ComplexDomainType()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 116 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(") : null; }\r\n        }\r\n\r\n");
            
            #line 119 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
      }
        else
        {
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 122 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.DomainType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 122 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 122 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" \r\n        {\r\n            get { return ");
            
            #line 124 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("; }\r\n        }\r\n\r\n");
            
            #line 127 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
      }
    }
            
            #line default
            #line hidden
            
            #line 128 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ImplementationPartialProperties(Model, readOnlyInterfaceName)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 129 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"

	if (Model.IsAggregateRoot() && !Model.IsSubClass()) 
    {

            
            #line default
            #line hidden
            this.Write("        DateTime? ");
            
            #line 133 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".CreateDateTime\r\n        {\r\n            get { return CreateDateTime; }\r\n        }" +
                    "\r\n\r\n        DateTime? ");
            
            #line 138 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".UpdateDateTime\r\n        {\r\n            get { return UpdateDateTime; }\r\n        }" +
                    "\r\n\r\n        string ");
            
            #line 143 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".UpdatedBy\r\n        {\r\n            get { return UpdatedBy; }\r\n        }\r\n\r\n");
            
            #line 148 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
  }

    foreach (var association in Model.Associations)
    {
        if (!association.Navigable)
            continue;

        if (association.OtherAssociationEnd().Multiplicity == Multiplicity.Many && association.Multiplicity == Multiplicity.One)
        {
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 157 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 157 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 157 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.IdentifierName()));
            
            #line default
            #line hidden
            this.Write("\r\n        { \r\n            get { return Domain.");
            
            #line 159 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.IdentifierType()));
            
            #line default
            #line hidden
            this.Write(".Create(this.");
            
            #line 159 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.IdentifierName()));
            
            #line default
            #line hidden
            this.Write("); }\r\n        }\r\n\r\n");
            
            #line 162 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
      }
        if (association.IsCollection())
        {
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 165 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Type("I", "", true)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 165 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 165 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" \r\n        { \r\n            get { return ");
            
            #line 167 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("; }\r\n        }\r\n\r\n");
            
            #line 170 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
      }
        else
        {
            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 173 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Type("I", "")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 173 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readOnlyInterfaceName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 173 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" \r\n        { \r\n            get { return ");
            
            #line 175 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(";} \r\n        }\r\n\r\n");
            
            #line 178 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
        }
    }

            
            #line default
            #line hidden
            this.Write("        #endregion\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 185 "C:\Dev\Intent.OpenSource\Modules\Intent.Modules.RichDomain\Templates\EntityStateInterface\DomainEntityStateInterfaceTemplate.tt"
 

public string GetInterfaces(Class umlClass) {
    if (umlClass.IsAggregateRoot())
    {
        return "IAggregateRoot, IVersionedEntity, IEntity";
    }
    if (umlClass.IsEntity())
    {
        return "IEntity";
    }
    return "";
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
