parameters:
- name: 'projects'
  type: 'object'

steps:
- ${{ each project in parameters.projects }}:
  # https://github.com/dotnet/sdk/issues/12160
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build ${{ project }}'
    env:
      DOTNET_NOLOGO: 1
    inputs:
        command: 'build'
        projects: '**/${{ project }}.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack ${{ project }}'
    env:
      DOTNET_NOLOGO: '1'
    inputs:
        command: 'pack'
        packagesToPack: '**/${{ project }}.csproj'

# - task: NuGetAuthenticate@0
#   displayName: 'nuget authenticate'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
      command: 'push'
      feedsToUse: 'select'
      includeNuGetOrg: 'false'
      publishVstsFeed: '4bb4c1b9-5b56-4972-8bac-0ad3fa64204e/intentarchitect-feed'
      allowPackageConflicts: true
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
