parameters:
- name: 'projects'
  type: 'object'

- name: 'noBuild'
  type: 'boolean'
  default: false

steps:
- ${{ each project in parameters.projects }}:

  # Documentation for `dotnet pack` says it should build automatically, but it doesn't right now:
  # https://github.com/dotnet/sdk/issues/12160
  - ${{ if ne('${{ parameters.noBuild }}', 'True') }}:

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build ${{ project }}'
      env:
        DOTNET_NOLOGO: 1
      inputs:
          command: 'build'
          projects: '**/${{ project }}.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack ${{ project }}'
    env:
      DOTNET_NOLOGO: '1'
    inputs:
        command: 'pack'
        packagesToPack: '**/${{ project }}.csproj'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
      command: 'push'
      feedsToUse: 'select'
      includeNuGetOrg: 'false'
      publishVstsFeed: '4bb4c1b9-5b56-4972-8bac-0ad3fa64204e/intentarchitect-feed'
      allowPackageConflicts: true
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
