using Intent.MetaModel.Domain;
using Intent.SoftwareFactory.Engine;
using Intent.SoftwareFactory.Templates;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Templates.Registrations.Templates.OneTemplateToManyModels
{
    public class Template : Intent.SoftwareFactory.Templates.IntentProjectItemTemplateBase<IEnumerable<IClass>>
    {
        public const string Identifier = "Templates.Registrations.OneTemplateToManyModels";

        public Template(IProject project, IEnumerable<IClass> models)
            : base(Identifier, project, models)
        {
        }

        public override DefaultFileMetaData DefineDefaultFileMetaData()
        {
            return new DefaultFileMetaData(
                overwriteBehaviour: OverwriteBehaviour.Always,
                codeGenType: CodeGenType.Basic,
                fileName: "OneTemplateToManyModels",
                fileExtension: "txt",
                defaultLocationInProject: "Templates\\Registrations\\OneTemplateToManyModels"
                );
        }

        public override string TransformText()
        {
            System.Text.StringBuilder result = new System.Text.StringBuilder();

            result.AppendLine("Generated by One Template To Many Models template");
            result.AppendLine($"This file is in the project : {Project.Name}");
            result.AppendLine($"Model is null: {Model == null}");
            result.AppendLine($"Model Count : {Model.Count()}");
            foreach (var x in Model)
            {
                result.AppendLine($"Model : {x.Name}");
            }

            return result.ToString();
        }
    }
}
