// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Typescript.ServiceAgent.AngularJs.Templates.ServiceProxy
{
    using Intent.Modelers.Services.Api;
    using Intent.Modules.Common.Templates;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    using Intent.Modules.Typescript.ServiceAgent.Contracts;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class TypescriptWebApiClientServiceProxyTemplate : IntentTypescriptProjectItemTemplateBase<IServiceModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 15 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"


            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 18 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(" {\r\n    export class ");
            
            #line 19 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" {\r\n        private readonly baseUrl: string;\r\n\r\n        static $inject = [\'$http" +
                    "\', \'Config\'];\r\n        constructor(\r\n            private readonly $http: ng.IHtt" +
                    "pService,\r\n            config: any\r\n        ) {\r\n            this.baseUrl = conf" +
                    "ig[\"");
            
            #line 27 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApiBasePathConfigKey));
            
            #line default
            #line hidden
            this.Write("\"];\r\n        }\r\n");
            
            #line 29 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
        foreach (var o in Model.Operations)
        {
            if (o.ReturnType != null)
            {


            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 36 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 36 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodDefinitionParameters(o)));
            
            #line default
            #line hidden
            this.Write("): ng.IPromise<");
            
            #line 36 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ConvertType(o.ReturnType.Type)));
            
            #line default
            #line hidden
            this.Write(">\r\n        {\r\n            const url = `${this.baseUrl}/api/");
            
            #line 38 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToLower().Replace("service","")));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 38 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("`;\r\n");
            
            #line 39 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
              if (GetHttpVerb(o) == HttpVerb.GET) { 
            
            #line default
            #line hidden
            this.Write("            return this.$http.get<");
            
            #line 40 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ConvertType(o.ReturnType.Type)));
            
            #line default
            #line hidden
            this.Write(">(url, { params: { ");
            
            #line 40 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodCallParametersForGet(o)));
            
            #line default
            #line hidden
            this.Write(" } }).then(result => result.data);\r\n");
            
            #line 41 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
              } else {
            
            #line default
            #line hidden
            this.Write("            return this.$http.post<");
            
            #line 42 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ConvertType(o.ReturnType.Type)));
            
            #line default
            #line hidden
            this.Write(">(url, ");
            
            #line 42 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodCallParametersForPost(o)));
            
            #line default
            #line hidden
            this.Write(").then(result => result.data);\r\n");
            
            #line 43 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
              }
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 45 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("\r\n        ");
            
            #line 51 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 51 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodDefinitionParameters(o)));
            
            #line default
            #line hidden
            this.Write("): ng.IPromise<void>\r\n        {\r\n            const url = `${this.baseUrl}/api/");
            
            #line 53 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToLower().Replace("service","")));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 53 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("`;\r\n            return this.$http.post<void>(url, ");
            
            #line 54 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodCallParametersForPost(o)));
            
            #line default
            #line hidden
            this.Write(").then(() => null);\r\n        }\r\n");
            
            #line 56 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            }
        }

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    angular.module(\"");
            
            #line 61 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AngularModule));
            
            #line default
            #line hidden
            this.Write("\").service(\"");
            
            #line 61 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("Proxy\", ");
            
            #line 61 "C:\Dev\Intent.Modules\Modules\Intent.Modules.Typescript.ServiceAgent.AngularJs\Templates\ServiceProxy\TypescriptWebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("Proxy);\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
