using Intent.MetaModel.Domain;
using Intent.SoftwareFactory.Engine;
using Intent.SoftwareFactory.Templates;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Templates.Registrations.Templates.OneTemplateToOneModel
{
    public class Template : Intent.SoftwareFactory.Templates.IntentProjectItemTemplateBase<IClass>
    {
        public const string Identifier = "Templates.Registrations.OneTemplateToOneModel";

        public Template(IProject project, IClass model)
            : base(Identifier, project, model)
        {
        }

        public override DefaultFileMetaData DefineDefaultFileMetaData()
        {
            return new DefaultFileMetaData(
                overwriteBehaviour: OverwriteBehaviour.Always,
                codeGenType: CodeGenType.Basic,
                fileName: $"OneTemplateToOneModel({Model.Name})",
                fileExtension: "txt",
                defaultLocationInProject: "Templates\\Registrations\\OneTemplateToOneModel"
                );
        }

        public override string TransformText()
        {
            System.Text.StringBuilder result = new System.Text.StringBuilder();

            result.AppendLine("Generated by One Template To One Model template");
            result.AppendLine($"This file is in the project : {Project.Name}");
            result.AppendLine($"Model is null: {Model == null}");
            result.AppendLine($"Model Type : {Model.Name}");

            return result.ToString();
        }
    }
}
