// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.ModuleBuilder.Templates.FactoryExtension
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.ModuleBuilder.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\FactoryExtension\FactoryExtensionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class FactoryExtensionTemplate : CSharpTemplateBase<Intent.ModuleBuilder.Api.FactoryExtensionModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using Intent.Engine;\r\nusing Intent.Modules.Common;\r\nusing Intent.Modules.Common.Plugins;\r\nusing Intent.Plugins.FactoryExtensions;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 18 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\FactoryExtension\FactoryExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    [IntentManaged(Mode.Fully, Body = Mode.Merge)]\r\n    public class ");
            
            #line 21 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\FactoryExtension\FactoryExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : FactoryExtensionBase\r\n    {\r\n        public override string Id => \"");
            
            #line 23 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\FactoryExtension\FactoryExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId()));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n        [IntentManaged(Mode.Ignore)]\r\n        public override int Order => 0;\r\n\r\n        /// <summary>\r\n        /// This is an example override which would extend the\r\n        /// <see cref=\"ExecutionLifeCycleSteps.AfterTemplateRegistrations\"/> phase of the Software Factory execution.\r\n        /// See <see cref=\"FactoryExtensionBase\"/> for all available overrides.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// It is safe to update or delete this method.\r\n        /// </remarks>\r\n        [IntentInitialGen]\r\n        protected override void OnAfterTemplateRegistrations(IApplication application)\r\n        {\r\n            // Your custom logic here.\r\n        }\r\n\r\n        /// <summary>\r\n        /// This is an example override which would extend the\r\n        /// <see cref=\"ExecutionLifeCycleSteps.BeforeTemplateExecution\"/> phase of the Software Factory execution.\r\n        /// See <see cref=\"FactoryExtensionBase\"/> for all available overrides.\r\n        /// </summary>\r\n        /// <remarks>\r\n        /// It is safe to update or delete this method.\r\n        /// </remarks>\r\n        [IntentInitialGen]\r\n        protected override void OnBeforeTemplateExecution(IApplication application)\r\n        {\r\n            // Your custom logic here.\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
}
