using Intent.SoftwareFactory.Engine;
using Intent.SoftwareFactory.Templates;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Templates.Registrations.Templates.NoModel
{
    public class Template : Intent.SoftwareFactory.Templates.IntentProjectItemTemplateBase
    {
        public const string Identifier = "Templates.Registrations.NoModel";

        public Template(IProject project)
            : base(Identifier, project)
        {
        }

        public override DefaultFileMetaData DefineDefaultFileMetaData()
        {
            return new DefaultFileMetaData(
                overwriteBehaviour: OverwriteBehaviour.Always,
                codeGenType: CodeGenType.Basic,
                fileName: "NoModel",
                fileExtension: "txt",
                defaultLocationInProject: "Templates\\Registrations\\NoModel"
                );
        }

        public override string TransformText()
        {
            System.Text.StringBuilder result = new System.Text.StringBuilder();

            result.AppendLine("Generated by No Model template");
            result.AppendLine($"This file is in the project : {Project.Name}");
            result.AppendLine($"Model is null: {Model == null}");

            return result.ToString();
        }
    }
}
