// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.ModuleBuilder.Templates.TemplateExtensions
{
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.CSharp.Templates;
    using Intent.Metadata.Models;
    using Intent.Templates;
    using Intent.ModuleBuilder.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TemplateExtensionsTemplate : CSharpTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using Intent.Modules.Common.Templates;\r\nusing System.Collections.Generic;\r\n\r\n[ass" +
                    "embly: DefaultIntentManaged(Mode.Fully)]\r\n[assembly: DefaultIntentManaged(Mode.F" +
                    "ully, Targets = Targets.Usings)]\r\n\r\nnamespace ");
            
            #line 14 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public static class ");
            
            #line 16 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 18 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
  foreach(var template in Templates)
    {
        var templateModel = ((TemplateRegistrationModel) template.Model); 
            
            #line default
            #line hidden
            
            #line 21 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
      if (templateModel.IsSingleFileTemplateRegistration()) { 
            
            #line default
            #line hidden
            this.Write("        public static string Get");
            
            #line 22 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(templateModel.Name.ToCSharpIdentifier()));
            
            #line default
            #line hidden
            this.Write("Name(this IIntentTemplate template)\r\n        {\r\n            return template.GetTy" +
                    "peName(");
            
            #line 24 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(template.Id, templateModel)));
            
            #line default
            #line hidden
            this.Write(".TemplateId);\r\n        }\r\n\r\n");
            
            #line 27 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
      } 
        else if (templateModel.IsCustomTemplateRegistration() && templateModel.GetModelType() == null) {

            
            #line default
            #line hidden
            this.Write("        public static string Get");
            
            #line 30 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(templateModel.Name.ToCSharpIdentifier()));
            
            #line default
            #line hidden
            this.Write("Name(this IIntentTemplate template)\r\n        {\r\n            return template.GetTy" +
                    "peName(");
            
            #line 32 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(template.Id, templateModel)));
            
            #line default
            #line hidden
            this.Write(".TemplateId);\r\n        }\r\n\r\n");
            
            #line 35 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"

        }
        else { 
            
            #line default
            #line hidden
            this.Write("        public static string Get");
            
            #line 38 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(templateModel.Name.ToCSharpIdentifier()));
            
            #line default
            #line hidden
            this.Write("Name<T>(this IIntentTemplate<T> template) where T: ");
            
            #line 38 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UseType(template.GetModelType())));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            return template.GetTypeName(");
            
            #line 40 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(template.Id, templateModel)));
            
            #line default
            #line hidden
            this.Write(".TemplateId, template.Model);\r\n        }\r\n\r\n        public static string Get");
            
            #line 43 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(templateModel.Name.ToCSharpIdentifier()));
            
            #line default
            #line hidden
            this.Write("Name(this IIntentTemplate template, ");
            
            #line 43 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UseType(template.GetModelType())));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n            return template.GetTypeName(");
            
            #line 45 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(template.Id, templateModel)));
            
            #line default
            #line hidden
            this.Write(".TemplateId, model);\r\n        }\r\n\r\n");
            
            #line 48 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
      } 
            
            #line default
            #line hidden
            
            #line 49 "C:\Dev\Intent.Modules\Modules\Intent.Modules.ModuleBuilder\Templates\TemplateExtensions\TemplateExtensionsTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
