// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.RichDomain.EntityFramework.Templates.DeleteVisitor
{
    using Intent.SoftwareFactory.MetaModels.UMLModel;
    using Intent.Modules.RichDomain;
    using Intent.Modules.Common.Templates;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class DeleteVisitorTemplate : IntentRoslynProjectItemTemplateBase<IEnumerable<Class>>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n\r\nusing System;\r\nusing Intent.Framework.Core;\r\nusing Intent.Framework.EntityFr" +
                    "amework.Interceptors;\r\nusing System.Collections.Generic;\r\n");
            
            #line 20 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DependencyUsings));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 24 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 26 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BoundedContextName));
            
            #line default
            #line hidden
            this.Write(@"DeleteVisitor : ICompositionDeleteVisitor
    {
        private readonly IList<object> _toDelete;

        public IList<object> ToDelete
        {
            get
            {
                return _toDelete;
            }
        }

        public void Reset()
        {
            _toDelete.Clear();
        }

        public ");
            
            #line 43 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BoundedContextName));
            
            #line default
            #line hidden
            this.Write("DeleteVisitor()\r\n        {\r\n            _toDelete = new List<object>();\r\n        " +
                    "}\r\n\r\n        public void Visit(IVisitable visitable)\r\n        {\r\n            Vis" +
                    "it((dynamic)visitable);\r\n        }\r\n\r\n");
            
            #line 53 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
 foreach (var model in Model) {
	   if (!model.IsEntity()) {
			continue;
       }

            
            #line default
            #line hidden
            this.Write("        public void Visit(");
            
            #line 58 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" state)\r\n        {\r\n");
            
            #line 60 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
 
        if (model.ParentClass != null)
        {

            
            #line default
            #line hidden
            this.Write("            Visit((");
            
            #line 64 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ParentClass.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(") state);\r\n");
            
            #line 65 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
 
        }

        foreach(var associationEnd in model.Associations)
        {
            if (associationEnd.Association.AssociationType ==  AssociationType.Composite && associationEnd.Association.ParentEnd == associationEnd)
            {
                if (associationEnd.IsCollection())
                {

            
            #line default
            #line hidden
            this.Write("            foreach (IVisitable item in state.");
            
            #line 75 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associationEnd.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                item.Accept(this);\r\n            }\r\n");
            
            #line 79 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"

                }
                else
                {
            
            #line default
            #line hidden
            this.Write("            if (state.");
            
            #line 83 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associationEnd.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n            {\r\n                ((IVisitable)state.");
            
            #line 85 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associationEnd.Name().ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(").Accept(this);\r\n            }\r\n");
            
            #line 87 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
                }
            }
        }

            
            #line default
            #line hidden
            this.Write("            _toDelete.Add(state);\r\n        }\r\n\r\n");
            
            #line 94 "C:\Dev\Intent.Modules\Modules\Intent.Modules.RichDomain.EntityFramework\Templates\DeleteVisitor\DeleteVisitorTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
