#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#nullable enable
using System.Collections.Generic;

namespace Intent.Modules.Common.CSharp.CodeToModelSynchronization;

public interface ICSharpSemanticComparisonNode
{
    IReadOnlyList<ICSharpSemanticComparisonNode> ChildNodes { get; }

    /// <summary>
    /// E.g. Added, Removed, Modified for the current node. Child nodes may have differences.
    /// </summary>
    CSharpDifferenceType DifferenceType { get; }

    /// <summary>
    /// If this current node or any of its child nodes have differences.
    /// </summary>
    bool HasDifferences();

    /// <summary>
    /// E.g. ClassDeclaration, MethodDeclaration, etc.
    /// </summary>
    CSharpSyntaxKind SyntaxKind { get; }

    /// <summary>
    /// The details of the node as it exists on the user's file system.
    /// </summary>
    public INodeDetails? Current { get; }

    /// <summary>
    /// The details of the node as generated by the software factory.
    /// </summary>
    public INodeDetails? Generated { get; }
}