// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MetadataNavigation.Uml.Templates.GenerateClass
{
    using Intent.MetaModel.Domain;
    using Intent.SoftwareFactory.Templates;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class Template : Intent.SoftwareFactory.Templates.IntentRoslynProjectItemTemplateBase<IClass>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            this.Write(" \r\n");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing Intent.CodeGen;\r\n");
            
            #line 14 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DependencyUsings));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nnamespace ");
            
            #line 16 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 18 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" \r\n    {\r\n\t\t//Attributes\r\n");
            
            #line 21 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
  foreach (var attribute in Model.Attributes)
    {
		string attributeType = Types.Get(attribute.Type);

            
            #line default
            #line hidden
            this.Write("        private ");
            
            #line 25 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 25 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPrivateMember()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n        public ");
            
            #line 27 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(" \r\n        {\r\n            get { return ");
            
            #line 29 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPrivateMember()));
            
            #line default
            #line hidden
            this.Write("; }\r\n            set\r\n            {\r\n\t\t\t    ");
            
            #line 32 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToPrivateMember()));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t        }\r\n\t\t}\r\n\r\n");
            
            #line 36 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
  }
            
            #line default
            #line hidden
            this.Write("\t\t//Associations\r\n");
            
            #line 38 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
	foreach (var associatedClass in Model.AssociatedClasses)
    {
		if (!associatedClass.IsNavigable) 
			continue;

		string associationType = GetAssociationType(associatedClass);
		string associtionName = Name(associatedClass);

            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 46 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associationType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 46 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associtionName.ToPrivateMember()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n        public virtual ");
            
            #line 48 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associationType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 48 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associtionName.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get\r\n            {\r\n\t\t\t\treturn ");
            
            #line 52 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associtionName.ToPrivateMember()));
            
            #line default
            #line hidden
            
            #line 52 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CollectionInitializer(associatedClass, associtionName.ToPrivateMember())));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            set\r\n            {    \r\n                ");
            
            #line 56 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associtionName.ToPrivateMember()));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n            }\r\n        }\r\n\r\n");
            
            #line 60 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
    }
            
            #line default
            #line hidden
            this.Write("\t\t//Operations\r\n");
            
            #line 62 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
  foreach (var operation in Model.Operations)
    {
        string returnType = GetReturnType(operation); 
        string parameterDefinitions = GetParameterDefinition(operation); 
		if (!operation.IsAbstract)
		{
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 68 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 68 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 68 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterDefinitions));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            throw new NotImplementedException(\"Replace with your im" +
                    "plementation...\");\r\n        }\r\n\r\n");
            
            #line 73 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
		}
		else
		{ 
            
            #line default
            #line hidden
            this.Write("        public abstract ");
            
            #line 76 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 76 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 76 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterDefinitions));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 78 "C:\Dev\Intent\IntentModuleExamples\MetadataNavigation.Uml\Templates\GenerateClass\Template.tt"
		}
    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
