// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Application.ServiceCallHandlers.Legacy.ServiceImplementation
{
    using Intent.SoftwareFactory.MetaModels.Class;
    using Intent.SoftwareFactory.MetaModels.Service;
    using Intent.SoftwareFactory.Templates;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ServiceImplementationTemplate : IntentRoslynProjectItemTemplateBase<ServiceModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\n");
            this.Write(" \r\n");
            
            #line 16 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"


            
            #line default
            #line hidden
            this.Write("\r\nusing System;\r\nusing System.Linq;\r\nusing System.Collections.Generic;\r\nusing Mic" +
                    "rosoft.Practices.Unity;\r\n");
            
            #line 23 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DependencyUsings));
            
            #line default
            #line hidden
            this.Write("\r\nusing Intent.CodeGen;\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamesp" +
                    "ace ");
            
            #line 28 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 30 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : I");
            
            #line 30 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private readonly IUnityContainer _container;\r\n\r\n        public ");
            
            #line 34 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(IUnityContainer container)\r\n        { \r\n            _container = container;\r\n   " +
                    "     }\r\n\r\n");
            
            #line 39 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
    foreach (var o in Model.Operations)
    {


            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 42 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.ReturnType.FullName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 42 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 42 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
 GetMethodDefinitionParameters(o); 
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 44 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
        foreach (var parameter in o.Parameters)
        {
            if (parameter.Type.TypeName.Contains("DTO") && parameter.Type.TypeName != "PagedSearchCriteriaDTO")
            {

            
            #line default
            #line hidden
            this.Write("            //");
            
            #line 48 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(".Validate(true);\r\n");
            
            #line 49 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("            \r\n            var sch = _container.Resolve<");
            
            #line 53 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Name));
            
            #line default
            #line hidden
            this.Write("SCH>();\r\n            ");
            
            #line 54 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"

        if (o.HasReturnType())
        {

            
            #line default
            #line hidden
            this.Write("return ");
            
            #line 57 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("sch.Handle(");
            
            #line 59 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
 GetMethodCallParameters(o); 
            
            #line default
            #line hidden
            this.Write(");\r\n        } \r\n\r\n");
            
            #line 62 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\ServiceImplementationTemplate.tt"
        
    }

            
            #line default
            #line hidden
            this.Write("\r\n        #region IDisposable Members\r\n\r\n        public void Dispose()\r\n        {" +
                    "\r\n            //dispose all resources\r\n        }\r\n\r\n        #endregion\r\n    }\r\n}" +
                    "");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 2 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"

void GetMethodDefinitionParameters(ServiceOperationModel o) 
{
	GetMethodDefinitionParameters(o, false);
}

void GetMethodDefinitionParameters(ServiceOperationModel o, bool withLeadingComma) 
{
	GetMethodDefinitionParameters(o.Parameters, withLeadingComma);
}

void GetMethodDefinitionParameters(List<ParameterModel> parameters, bool withLeadingComma) 
{
	    for(int i = 0; i < parameters.Count; i++) 
	{ 
		ParameterModel p = parameters[i];
		if (withLeadingComma || (!withLeadingComma && i != 0))
        {
			
        
        #line default
        #line hidden
        
        #line 20 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 20 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"

        } 
	
        
        #line default
        #line hidden
        
        #line 22 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Type.FullName));

        
        #line default
        #line hidden
        
        #line 22 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 22 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 22 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"

	}	
}


        
        #line default
        #line hidden
        
        #line 28 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"


void GetMethodCallParameters(ServiceOperationModel o) 
{
	GetMethodCallParameters(o, false);
}

void GetMethodCallParameters(ServiceOperationModel o, bool withLeadingComma) 
{
	GetMethodCallParameters(o.Parameters, withLeadingComma);
}

void GetMethodCallParameters(List<ParameterModel> parameters, bool withLeadingComma)
{
    for(int i = 0; i < parameters.Count; i++) 
	{ 
		ParameterModel p = parameters[i];
		if (withLeadingComma || (!withLeadingComma && i != 0))
        {
			
        
        #line default
        #line hidden
        
        #line 47 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 47 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"

        } 
	
        
        #line default
        #line hidden
        
        #line 49 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 49 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"

	}

}

void GetMethodCallParameters(ServiceOperationModel o, bool withLeadingComma, string prefix)
{
	List<ParameterModel> parameters = o.Parameters;

    for(int i = 0; i < parameters.Count; i++) 
	{ 
		ParameterModel p = parameters[i];
		if (withLeadingComma || (!withLeadingComma && i != 0))
        {
			
        
        #line default
        #line hidden
        
        #line 63 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(", ");

        
        #line default
        #line hidden
        
        #line 63 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"

        } 

        
        #line default
        #line hidden
        
        #line 65 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(prefix + p.Name));

        
        #line default
        #line hidden
        
        #line 65 "C:\Dev\Intent\IntentArchitect\Modules\Intent.Modules.Application.ServiceCallHandlers\Legacy\ServiceImplementation\./../Services.ttinclude"

	}
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
