// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.IdentityServer.Templates.Clients
{
    using Intent.Modules.Common.Templates;
    using System;
    using System.IO;
    using System.Diagnostics;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules\Modules\Intent.Modules.IdentityServer\Templates\Clients\IdentityServerClientsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class IdentityServerClientsTemplate : IntentRoslynProjectItemTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\nusing System.Collections.Generic;\r\nusing IdentityServer3.Core.Models;\r\n\r\n[asse" +
                    "mbly: DefaultIntentManaged(Mode.Ignore)]\r\n\r\nnamespace ");
            
            #line 18 "C:\Dev\Intent.Modules\Modules\Intent.Modules.IdentityServer\Templates\Clients\IdentityServerClientsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(@"
{
    public static class Clients
    {
        public static List<Client> Get()
        {
            return new List<Client>
            {
				// Example client:
				/*
				new Client
                {
                    Enabled = true,
                    ClientName = ""Example Client"",
                    ClientId = ""example_client"",

                    Flow = Flows.ResourceOwner,
					RequireConsent = false,

                    AllowedCorsOrigins = new List<string> { ""*"" },

                    AllowAccessToAllScopes = true,
					AccessTokenType = AccessTokenType.Jwt
                }
				*/
            };
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
