// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.HttpServiceProxy.Templates.Proxy
{
    using System;
    using System.Linq;
    using System.Collections;
    using System.Collections.Generic;
    using Intent.Modules.Common.Templates;
    using Intent.Modelers.Services.Api;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class WebApiClientServiceProxyTemplate : IntentRoslynProjectItemTemplateBase<ServiceModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Configuration;\r\nusing System.Linq;\r\nusing System.Net." +
                    "Http;\r\nusing System.Net.Http.Headers;\r\nusing System.Threading.Tasks;\r\n");
            
            #line 16 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DependencyUsings));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n[assembly: DefaultIntentManaged(Mode.Fully)]\r\n\r\nnamespace ");
            
            #line 20 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class ");
            
            #line 22 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 22 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetServiceInterfaceName()));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private readonly ");
            
            #line 24 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetHttpClientServiceInterfaceName()));
            
            #line default
            #line hidden
            this.Write(" _httpClientService;\r\n\r\n        public ");
            
            #line 26 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 26 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetHttpClientServiceInterfaceName()));
            
            #line default
            #line hidden
            this.Write(" httpClientService)\r\n        {\r\n            _httpClientService = httpClientServic" +
                    "e;\r\n        }\r\n");
            
            #line 30 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

    foreach (var operation in Model.Operations)
    {

            
            #line default
            #line hidden
            
            #line 34 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

        // Asynchronous versions:
        if (operation.ReturnType != null)
        {

            
            #line default
            #line hidden
            this.Write("\r\n        public async Task<");
            
            #line 40 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationReturnType(operation)));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 40 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 40 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationDefinitionParameters(operation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return await new Task<");
            
            #line 42 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationReturnType(operation)));
            
            #line default
            #line hidden
            this.Write(">(() => ");
            
            #line 42 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 42 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationCallParameters(operation)));
            
            #line default
            #line hidden
            this.Write("));\r\n        }\r\n");
            
            #line 44 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

        }
        else // if (operation.ReturnType != null)
        {

            
            #line default
            #line hidden
            this.Write("\r\n        public async void ");
            
            #line 50 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 50 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationDefinitionParameters(operation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            await new Task(() => ");
            
            #line 52 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 52 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationCallParameters(operation)));
            
            #line default
            #line hidden
            this.Write("));\r\n        }\r\n");
            
            #line 54 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
 
        } // if (operation.HasReturnType())

        // Synchronous versions:

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 60 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationReturnType(operation)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 60 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 60 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationDefinitionParameters(operation)));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            try\r\n            {\r\n                const string reques" +
                    "tUri = \"/api/");
            
            #line 64 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 64 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n                var response = _httpClientService.PostAsJsonAsync(\r\n       " +
                    "             targetApplicationName: \"");
            
            #line 67 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationName));
            
            #line default
            #line hidden
            this.Write("\",\r\n                    requestUri: requestUri,\r\n                    value: new\r\n" +
                    "                    {\r\n");
            
            #line 71 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

                        foreach (var parameter in operation.Parameters)
                        {

            
            #line default
            #line hidden
            this.Write("                        ");
            
            #line 75 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 76 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

                        } // foreach (var parameter in operation.Parameters)

            
            #line default
            #line hidden
            this.Write(@"                    }).Result;

                if (!response.IsSuccessStatusCode)
                {
                    throw new WebApiClientServiceProxyRemoteException(
                        response.StatusCode,
                        response.ReasonPhrase,
                        $""Request to {new Uri(new Uri(_httpClientService.GetBaseAddress(""");
            
            #line 86 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationName));
            
            #line default
            #line hidden
            this.Write("\")), requestUri).AbsoluteUri} failed with status code {(int)response.StatusCode} " +
                    "{response.ReasonPhrase}.\\n\\n\" +\r\n                        $\"{response.Content.Rea" +
                    "dAsStringAsync().Result}\");\r\n                }\r\n");
            
            #line 89 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

            if (operation.ReturnType != null)
            {

            
            #line default
            #line hidden
            this.Write("\r\n                return response.Content.");
            
            #line 94 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReadAs(operation)));
            
            #line default
            #line hidden
            this.Write(".Result;\r\n");
            
            #line 95 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

            } // if (operation.ReturnType != null)

            
            #line default
            #line hidden
            this.Write(@"            }
            catch (AggregateException aggregateException)
            {
                if (aggregateException.InnerExceptions.Count == 1)
                {
                    throw aggregateException.InnerExceptions.Single();
                }

                throw;
            }
        }
");
            
            #line 109 "C:\Dev\Intent.Modules\Modules\Intent.Modules.HttpServiceProxy\Templates\Proxy\WebApiClientServiceProxyTemplate.tt"

    } // foreach (var operation in Model.Operations)

            
            #line default
            #line hidden
            this.Write("\r\n        public void Dispose()\r\n        {\r\n            // NOP - Required for int" +
                    "erface implementation\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
