using System.Collections.Generic;

namespace Intent.Modules.Common.Templates
{
    /// <summary>
    /// Helpers for C# code.
    /// </summary>
    public static class CSharp
    {
        /// <summary>
        /// List of C# keywords as per <see href="https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/"/>.
        /// </summary>
        public static readonly HashSet<string> ReservedWords = new HashSet<string>
        {
            "abstract",
            "as",
            "base",
            "bool",
            "break",
            "byte",
            "case",
            "catch",
            "char",
            "checked",
            "class",
            "const",
            "continue",
            "decimal",
            "default",
            "delegate",
            "do",
            "double",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "false",
            "finally",
            "fixed",
            "float",
            "for",
            "foreach",
            "goto",
            "if",
            "implicit",
            "in",
            "int",
            "interface",
            "internal",
            "is",
            "lock",
            "long",
            "namespace",
            "new",
            "null",
            "object",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "ref",
            "return",
            "sbyte",
            "sealed",
            "short",
            "sizeof",
            "stackalloc",
            "static",
            "string",
            "struct",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "uint",
            "ulong",
            "unchecked",
            "unsafe",
            "ushort",
            "using",
            "using static",
            "virtual",
            "void",
            "volatile",
            "while"
        };
    }
}
